# Generated by Django 2.2 on 2020-03-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=512)),
                ('api_app_id', models.CharField(max_length=512)),
                ('user_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('default_channel', models.CharField(blank=True, max_length=1024, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.CharField(blank=True, max_length=1024, null=True)),
                ('source_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Connector.SSCConnector')),
            ],
        ),
        migrations.CreateModel(
            name='SlackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('channel', models.CharField(max_length=1024)),
                ('is_complete', models.BooleanField(default=False)),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Slack.Slack')),
            ],
        ),
    ]
