# Generated by Django 2.2 on 2020-01-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slack',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
