# Generated by Django 2.2 on 2020-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZOHO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohomodel',
            name='org_id',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
