# Generated by Django 2.2 on 2020-02-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jitbit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitbitmodel',
            name='domain',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
