# Generated by Django 2.2 on 2020-01-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connector', '0003_sscconnector_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscconnector',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
