# Generated by Django 2.2 on 2020-02-28 06:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Connector', '0004_sscconnector_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('app_logo', models.ImageField(upload_to='static/logos/')),
                ('required_fields', jsonfield.fields.JSONField()),
            ],
        ),
    ]
